### ISSUE TITLE
Customize theme

### ISSUE THREAD

**Issue by juliocanares** [ant-design/parcel-antd#1]
using ` .lessrc` with parcel doesn't work

```
{
    "modifyVars": {
        "@primary-color": "#1DA57A"
    }
}
```

is there any other way to do it?

**Comment by afc163** [comment]
https://github.com/ant-design/parcel-antd/pull/2

The workaround for now is following https://ant.design/docs/react/customize-theme#2)-Overriding-Less-variables-(alternative-way).

**Comment by juliocanares** [comment]
cool gonna try, thank u

**Comment by horsfallnathan** [comment]
#2 @afc163  this leads to bloat  as stated in the antd docs. Is there a better way now?

**Comment by Bonerdelli** [comment]
Downgrading less to 2.7.2 helped me
