### ISSUE TITLE
 Inline JavaScript is not enabled. Is it set in your options?

### ISSUE THREAD

**Issue by jonlepage** [ant-design/parcel-antd#19]
not working ???
 Inline JavaScript is not enabled. Is it set in your options?
![image](https://user-images.githubusercontent.com/24865815/79519626-60d47080-8022-11ea-8775-3c7c8802b8d9.png)

**Comment by jonlepage** [comment]
dam ok after hour here solution
https://juejin.im/post/5dedee2ce51d455817765f2e
```json
{
  "javascriptEnabled": true
}
```

**Comment by Nxtra** [comment]
Indeed update `craco.config.js` to : 
```
const CracoLessPlugin = require("craco-less");

module.exports = {
  plugins: [
    {
      plugin: CracoLessPlugin,
      options: {
        lessLoaderOptions: {
          lessOptions: {
            modifyVars: {},
            javascriptEnabled: true,
          },
        },
      },
    },
  ],
};
```

**Comment by StallionV** [comment]
> https://juejin.im/post/5dedee2ce51d455817765f2e

hello @djmisterjon the link you shared does not work.
Can you show how you got it to work

**Comment by jonlepage** [comment]
> > https://juejin.im/post/5dedee2ce51d455817765f2e
> 
> hello @djmisterjon the link you shared does not work.
> Can you show how you got it to work

Hum not remember sry,... 
I moved to **Vitejs** instead of Parcel ! 
No more issue and no more config !!
https://vitejs.dev

**Comment by quantuminformation** [comment]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/216566/177124684-391864f3-18a9-441c-907c-4719687f2427.png">
having a terrible time in vite
