### ISSUE TITLE
compiling Error

### ISSUE THREAD

**Issue by zhayes** [ant-design/parcel-antd#8]
![image](https://user-images.githubusercontent.com/17758062/37270891-852663ee-260b-11e8-942e-a3a5d76f39ad.png)

![image](https://user-images.githubusercontent.com/17758062/37270910-9f20c91a-260b-11e8-9b83-920a8c6fc264.png)

![image](https://user-images.githubusercontent.com/17758062/37270933-b5d9ba40-260b-11e8-9d11-47bb608b198c.png)

![image](https://user-images.githubusercontent.com/17758062/37270960-d8b39612-260b-11e8-9e48-f54f79f5dacd.png)

**Comment by afc163** [comment]
https://github.com/ant-design/parcel-antd/blob/master/package.json#L16 Use less@2.x for now.
